language: node_js
node_js:
- '8'
notifications:
  email: false
deploy:
  provider: npm
  email: dev@launchpadlab.com
  api_key:
    secure: QjQodl2Iw+PaZ76B5+2Ka/6bxmrT8fq6kihlw9SZgz/z6YT2ccmPP+pYmiYqqY2UJQUX2pWpPlWCbPCkwwXnnUrhRNg4cEpzG+VY8RG6bzD4qrts8IRSOtFBZDeX3oXBvH+B3vouewr290cryq3vMSWdm8Brb3IeI67DPYnpYKUbAos5c4UjPTwFILgk2rcuY6FPMn5buzb+0DUwK0eVp8rtS+WXOKOKz/4fl/o3c+qJm57GN++0r/0PaDdud6puJLIfCEhvq1udm4dJGd/Z2Cn/BahJ+VXjH9cPu7MmuSaw1urmrWvBusZKOXD+6DgEn5BCasrfJ1g5JAXiTid4trgp0VeuGBpeurZtd7JND0hiOBnPdJOSeO3CeeGn5Bq6WM6KHRmsiSwhLLELOQEXbxnl3aRO4FHhpXXmq5OAynq2UILUpmc5lWXDuUciAJuJONPhPkkj5Aq/Qa/c8E1gI4Llkpo/uSfVoF/MrQaKvtnBHSGpoV+PqnuXbsN0QjQvHLjP+M6XEz3r0xgD1gAFS9UfylTXewzOs29z6A4a2TeCo1msLKNYOpf7Nrci8KHRLlXJsy73vFi1RkhBBH9ZVU+mJM6SpuaErU237JXn4F5UdqpKR70YTn2s62fiA7zxG11UXE2Cg7L7kyPO9Tg4EFF30ELmS0w/pWI0B3Sp6aU=
  on:
    branch: master
  skip_cleanup: true
