language: node_js
node_js:
- '8'
notifications:
  email: false
deploy:
  provider: npm
  email: dev@launchpadlab.com
  api_key:
    secure: OW0zUf2p/g6bxyFBRwIuiLr32Cu8SAJD99pe4sO7R3yvaxTw+wAVarBuls4YaV2r5SsIrUIMrCjTjy5P0PtffJa7gfhs6FL0XhtCqKRZ9mZ5yB0aSn/a05XzQrvto7EgBBb0/7xzAJLqzeJr2sCD9E//YNaJ6LDTlJKwV7uCWdRPsuDQEyIkVaXXIfp7Lp7symcLXft8F7Fhh/Hbf/H+k75xXMd/WxR6E92cKOnRuvsuq5ieajcS1rGvETPkVEjt1F3hvGgEg8QvpWe4vgrCmnTp8N8E39y3Ozb92xakjLKYuJy8ln5ZlSr2Cd88IHlM7XvhbMASLBdoL5mPu+ruxK4HKIHPin6yRk625SstsWE1liqPdjUs49ttzBO9Skoq7ciX27ZOsdk9g9SR+YIjG+hzjSh0HaTdNsVoXjUScP57tz5NSOCsqdsAuUvClEd92J/j8P7GXn2ga7KTDnrnTKrweSAZKXsLIdx8tJ+gOvCLskEh+AnKeVGXinmazuTQ4gE1TuTFQa+AJs6XnSaDcVTyRe2J9y34ESy1yobUuTF3a+uqLLLlsil5O4mWnMlfuiIv089CbDlwzPxmqHMZT2hQS5rXSiFlF+PIia+Y0zw/koG8Ns+y7Ua/z/Gsa6whFiXwOlaiHmornzq4l+tB2B2exIOlo1Uf0CxAvFO3VTA=
  on:
    branch: master
  skip_cleanup: true
