language: node_js
node_js:
- '8'
before_script:
  - 'yarn lint'
notifications:
  email: false
deploy:
  provider: npm
  email: dev@launchpadlab.com
  api_key:
    secure: iCN1lPxy3t7kERm2QKIFTgJlS/r0S+0RNrUw+t1+lWRjHM6gyYKXxQcSsUOp5ILW8he4MDQAtQNQk3vF9umishPY06PIOW+yKMk8JbBdzA6SXVKDNBCK3WfoB3vNTtXp+ESM+7Gd44LAnDRK/XyrQknZDlIq2iep+tT9SVCYpisF9LVXIHXDJt9nNHAhUfdcggUZJA4HPgqb9zGtK2Ev7KzK/eCy///+AWSwXrhuNRp1yYkdRxBKUodBqAL9u/I/wW0Ah0kOWkD7cP7RCd3kGGX1h7eWGoHl7fjYP+85IwU8W6ZP/PpLuDL6sOcIEtIN+DKB7uuzcMaO5v4xI0Gr8KUpGunLT7/H0izEjPjX3LYD1MMUQMpGPBvfyysuvc6RyvTHijjoHphenlEt+7bpsH1y3RGN9ptJVzRScJIVQSGzyaupE8a6Xut4CxY0k+VOLBweLCNgTlSVDIQrrfFGI8RTNdT0zYmsk6Qek3iPXXNZEZx+8UAAQPloj1R6nA0wOn71q5fR+M+PBsjF9xsF9mqhAz6b70XnCgrzZfngcwxVnHjWx81oOwL8F575v9mskO6WQMqK8WcIVB41lXHih/9CfwzCBIfeMOmZ6lmTQexskCUBy+j6M8iNQInE4wNogJC3FVj9QPuwY6aOGIOKHOFVibtAg5WV4aBOdwXjwrE=
  on:
    branch: master
  skip_cleanup: true