language: node_js
node_js:
- '8'
notifications:
  email: false
deploy:
  provider: npm
  email: dev@launchpadlab.com
  api_key:
    secure: Df6CVLwZWmaTnsA/W8nV+VOMfQMi7uXxtIdAlABa2JmE20noQwa4fw+/VsnKi+DHqMeeF2y8bQcFXFVnFiYCNrfjs6vN1zPoG+jq/ek0VRub6rJYPmZIZd49fy7d+dWzKPJ/u7/9JxsHPSqLKarPjAPxmv+lOLJWIMzmA0+minJXDdBPqZnpBf5d+8GWr66vAp4HfkguWeEyLn9/yF94ZoDNLr8mQfe8LPNxhFCEmuWYLOW7BVpcWkiJy3SPkcJOjmD1US0pxydYtJaeLwgDk70kXlB3L18lTL5CTvixWpjlgYm0bz+HBLTnXtmPyQRi2aWcjaIfVwvDuq+pluS3jeOI44FqrbZ5U8CpBhKxe8Ts6AOO7LbN4g2Vr8nscOWIeEqYRG/6sM20LitAIaFH7jWkVWm98EBZgkQRNn0Bdg4BZBI/QT+xrtXd3W91MCEDTFQfi45507K9oH1suZxEECIIqio4cmrOR51w6q30bwGBHnacuaBGGKQHHuBjslOAK976IQSMlZ+R6oLCPVpN3SYF6VLLL7s9o08bPlXm70wE3Fw9zNXlTGvwVz66i0MtgT7TJdHgRrIpFE9C8SIYU1wK252LT6uu0P4YQqMpmNSg5rCBBGMB0O5/1CQigwQNBMqKsyty5yp2Tmj22goBV38cqqxaeufxO62oQGMQlZQ
  on:
    branch: master
  skip_cleanup: true
